semi: true
tabWidth: 2
useTabs: false
printWidth: 120
singleQuote: true
endOfLine: auto
trailingComma: all
bracketSpacing: true
jsxSingleQuote: true
arrowParens: always
bracketSameLine: false
quoteProps: as-needed
singleAttributePerLine: true
plugins:
  - prettier-plugin-tailwindcss
